language: node_js

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email:
    - adavijit@yahoo.com

node_js:
  - '20'

install:
  - yarn

script:
  - yarn prettier
  - yarn lint
  - yarn test

after_success: 'yarn coveralls'
